import 'dart:typed_data';
import 'package:syncfusion_flutter_pdf/pdf.dart';

/// PDF-specific half of the bulk price-list import -- reconstructs a plain
/// `List<List<String>>` grid (the same shape excel_import.dart produces)
/// from a text-layer PDF, purely from word geometry. No OCR, no ML: a PDF
/// generated by office/ERP software (the overwhelming majority of supplier
/// price lists, as opposed to a scanned photo) embeds each word as text
/// with an exact x/y position -- from there this only has to decide which
/// words sit on the same visual row (grouped by y-position) and, within a
/// row, which words belong to the same "cell" (close together on x)
/// versus a new one (a wide horizontal gap) -- the same whitespace-
/// alignment technique classic PDF table extractors use.
///
/// Rows are clustered by y-position *ourselves*, in [_groupIntoRows],
/// rather than trusting Syncfusion's own per-line grouping
/// (`TextLine.wordCollection`) -- testing against a synthetic table PDF
/// showed the library's own line detection can split one visual row into
/// two fragments over a sub-pixel baseline difference between columns
/// (common in real right-aligned price columns), which silently dropped
/// whole rows under the old mode-count-filter approach. Clustering by a
/// tolerance band we control is more forgiving of exactly that kind of
/// real-world misalignment.
///
/// This is inherently less reliable than Excel's already-gridded cells --
/// a genuinely inconsistent layout can still throw the column count off
/// for a given row. Rather than guess at a mismatched row, rows whose cell
/// count doesn't match the sheet's most common ("mode") column count are
/// dropped, and [PdfGridResult] reports how many were lost so the review
/// screen can be honest about it instead of silently losing rows. A
/// scanned/photographed PDF has no embedded text at all and produces an
/// empty grid -- that needs real OCR, a different, much bigger project,
/// not attempted here.
class PdfGridResult {
  final List<List<String>> grid;
  final int totalRows;
  final int keptRows;

  const PdfGridResult({required this.grid, required this.totalRows, required this.keptRows});
}

class _Word {
  final String text;
  final double left;
  final double right;
  final double yCenter;
  final double height;

  const _Word({required this.text, required this.left, required this.right, required this.yCenter, required this.height});
}

/// Two words are on the same row if their vertical centers are within
/// this fraction of the shorter word's height -- generous enough to
/// absorb normal baseline/font-metric jitter between columns, tight
/// enough not to merge two genuinely different table rows together.
const _rowToleranceFraction = 0.6;

/// A gap wider than this (in PDF points, ~1/72in) between two consecutive
/// words on the same row starts a new cell -- narrower than that, they're
/// just spaced-out words within the same cell (e.g. a multi-word product
/// name). Tuned generously since a too-small threshold splits names into
/// several cells, which is a worse failure than occasionally merging two
/// genuinely-close columns (the review screen's remap dropdowns and
/// preview table catch either kind of mistake anyway).
const _cellGapThreshold = 8.0;

List<List<_Word>> _groupIntoRows(List<_Word> words) {
  final sorted = [...words]..sort((a, b) => a.yCenter.compareTo(b.yCenter));
  final rows = <List<_Word>>[];
  for (final w in sorted) {
    if (rows.isEmpty) {
      rows.add([w]);
      continue;
    }
    final currentRow = rows.last;
    final refY = currentRow.map((r) => r.yCenter).reduce((a, b) => a + b) / currentRow.length;
    final tolerance = currentRow.map((r) => r.height).reduce((a, b) => a < b ? a : b) * _rowToleranceFraction;
    if ((w.yCenter - refY).abs() <= tolerance) {
      currentRow.add(w);
    } else {
      rows.add([w]);
    }
  }
  return rows;
}

List<String> _rowToCells(List<_Word> row) {
  final sorted = [...row]..sort((a, b) => a.left.compareTo(b.left));
  final cells = <String>[];
  var current = sorted.first.text.trim();
  var currentRight = sorted.first.right;
  for (final w in sorted.skip(1)) {
    final gap = w.left - currentRight;
    if (gap > _cellGapThreshold) {
      cells.add(current);
      current = w.text.trim();
    } else {
      current = '$current ${w.text.trim()}';
    }
    currentRight = w.right;
  }
  cells.add(current);
  return cells;
}

PdfGridResult gridFromPdfBytes(Uint8List bytes) {
  final document = PdfDocument(inputBytes: bytes);
  try {
    final textLines = PdfTextExtractor(document).extractTextLines();
    // Flatten every word out of Syncfusion's own line grouping and redo
    // row clustering ourselves -- see the class doc comment for why.
    // Multi-page documents get a large synthetic y-offset per page so
    // pages never interleave, since PDF coordinates reset per page.
    final words = <_Word>[];
    for (final line in textLines) {
      final pageOffset = line.pageIndex * 100000.0;
      for (final w in line.wordCollection) {
        if (w.text.trim().isEmpty) continue;
        words.add(_Word(
          text: w.text,
          left: w.bounds.left,
          right: w.bounds.left + w.bounds.width,
          yCenter: pageOffset + w.bounds.top + w.bounds.height / 2,
          height: w.bounds.height <= 0 ? 10 : w.bounds.height,
        ));
      }
    }

    if (words.isEmpty) {
      return const PdfGridResult(grid: [], totalRows: 0, keptRows: 0);
    }

    final rows = _groupIntoRows(words).map(_rowToCells).toList();

    // Most tables have a consistent column count -- rows that don't match
    // it are usually titles, page headers/footers, or a misread row.
    final counts = <int, int>{};
    for (final r in rows) {
      counts[r.length] = (counts[r.length] ?? 0) + 1;
    }
    final modeCount = counts.entries.reduce((a, b) => a.value >= b.value ? a : b).key;
    final kept = rows.where((r) => r.length == modeCount).toList();

    return PdfGridResult(grid: kept, totalRows: rows.length, keptRows: kept.length);
  } finally {
    document.dispose();
  }
}
